name: deltafunction
favicon: null
layout_spectrum: 0.639395060017705
typography_spectrum: 0.7040284385439008
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#9D2D3C'
    - '#DDE4DD'
    - '#BCAB47'
    - '#6B574B'
    - '#160600'
  brandStrength: 0.8320079606492072
  lightness: 0.34568281774409115
  saturation: 0.7075476043391973
  rhythmicContrast: 0.8796061514876783
purpose: []
